### ISSUE TITLE
the issue of sqli rule recommendation 

### ISSUE THREAD

**Issue by ntochizawa** [deep-security/aws-waf#11]
Hi 
I tested the last commit(cac192b) and tool recommended the sqli rules in spite of the existence of sqli vulnerabilities.
It seems not to push the result of recommendation scan.
(Recommendation status is False)

*Result log is bellow.
[root@XXXXX aws-waf-cac192b]# python ds-to-aws-waf.py sqli -u apiuser -p XXXXX -t User --create-match
[root@XXXXX aws-waf-cac192b]# python ds-to-aws-waf.py sqli -u apiuser -p XXXXX -t User -l -r ap-northeast-1
Requesting information from Deep Security about your deployment
[2016-04-15 08:23:27]   Calling DPIRuleRetrieveAll. This may take 15-30 seconds as the call returns a substantial amount of data
************************************************************************
Completed recommendation phase
   Instance     Recommendation  Suggested WACL
************* ellipsis *************
************* ellipsis *************
   i-be76d621   False   a960c8a1-75df-48e4-aea8-bc26f4961c1b
************* ellipsis *************
************* ellipsis *************
************************************************************************

But when I tested 5ca4816 in same envionment, tool recommended the sqli rules to same instance.
(Recommendation status is True)

*Result log is bellow.
[root@XXXXX aws-waf-5ca4816]# python ds-to-aws-waf.py sqli -u apiuser -p XXXXX -t User --create-match
[root@XXXXX aws-waf-5ca4816]# python ds-to-aws-waf.py sqli -u apiuser -p XXXXX -t User -l -r ap-northeast-1
Requesting information from Deep Security about your deployment
************************************************************************
Completed recommendation phase
   Instance     Recommendation  Suggested WACL
************* ellipsis *************
************* ellipsis *************
   i-be76d621   True    a960c8a1-75df-48e4-aea8-bc26f4961c1b
************* ellipsis *************
************* ellipsis *************
************************************************************************
Successfully updated WACL [a960c8a1-75df-48e4-aea8-bc26f4961c1b]

Please check it.

ntochizawa

**Comment by marknca** [comment]
@ntochizawa I've expanded the regex filters to include more Deep Security rules. Should make recommendations more often as of commit [7f0f35448599cfb214212d7093effb7fc554c1d4](https://github.com/deep-security/aws-waf/commit/7f0f35448599cfb214212d7093effb7fc554c1d4)
