### ISSUE TITLE
cannot set double-byte tenant name in -t option

### ISSUE THREAD

**Issue by tapun** [deep-security/aws-waf#12]
Japanese customer can set DSaaS tenant name as double-byte name but this tool cannot set double-byte tenant name so cannot use this tool.
Is there any way to use this tool in double-byte DSaaS tenant?

**Comment by marknca** [comment]
@tapun thanks for raising this. We're investigating the issue now and hope to have some results soon

**Comment by marknca** [comment]
@tapun we've identified and resolved the issue. The fix is now integrated into the master branch. Please `git pull` to get the latest.
