### ISSUE TITLE
ds-to-aws-waf.py can't work

### ISSUE THREAD

**Issue by ntochizawa** [deep-security/aws-waf#14]
Hi !

I have verified the latest commit(7f0f354), and it can't work as below.
I seem to be lack of the module - lib.rules.

Please check the codes.

<result output>
[root@ip-xxxxx aws-waf-7f0f354]# python27 ds-to-aws-waf.py xss -u xxxxx -p xxxxx -t xxxxx --create-match --verbose
Traceback (most recent call last):
  File "ds-to-aws-waf.py", line 19, in <module>
    import lib.rules
ImportError: No module named rules
[root@ip-xxxxx aws-waf-7f0f354]

<environment>
Script server
  4.4.11-23.53.amzn1.x86_64
  
Best regards,
ntochizawa

**Comment by marknca** [comment]
@ntochizawa can you please verify that directory ```lib``` exists and that the ```rules.py``` file is present?

**Comment by ntochizawa** [comment]
I have verified the directory “lib” exists, but “rules.py” file is not in it.
Please advise to resolve the error..

**Comment by marknca** [comment]
Updated commit to include missing file. 

Resolve with commit https://github.com/deep-security/aws-waf/commit/c46a1916551157deb19269003d15c08ba0661193
