### ISSUE TITLE
Average number of ACLs & Rules in a typical scenario

### ISSUE THREAD

**Issue by gaia** [deep-security/aws-waf#18]
- [X ] I will be using Deep Security version ____ Deep Security as a Service

- [N/A] I'm using the latest version of this repo

- [N/A] My Deep Security Manager has a self-signed or non-validating SSL certificate

To protect a LAMP server behind Deep Security as a Service, how many WEB ACLs and Rules are **typically deployed**?

**Comment by marknca** [comment]
Apologies on the delayed response here. The tool will roll out 2 rules (one SQLi, one XSS) for 1 web ACL. That complements the IPS features of Deep Security as a Service nicely.
