### ISSUE TITLE
 It does not include the Query string to the condition of sqli.

### ISSUE THREAD

**Issue by fnifni** [deep-security/aws-waf#9]
I tried --create-match of sqli in 5ca4816.

The conditions that have been created , 
"Part of the request to filter on" to "Query String" does not have the specified.
Is this intended ?

I am considered to be included the code of SQL injection to query strings.

**Comment by marknca** [comment]
@fnifni can you please clarify what you're looking to validate?

The match condition created should be:

![screen shot 2016-03-29 at 10 40 22 pm](https://cloud.githubusercontent.com/assets/39484/14130199/4e6a5f9c-f5ff-11e5-8e6d-2bbd2eeff73b.png)

**Comment by fnifni** [comment]
My explanation was not correct .
querystrings the does not detect the Request , such as the following not to URL decode .
===
http://www.fnifni.com:80/ua.php?id=1%20UNION%20ALL%20SELECT%20NULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL--%20-
===

This setting condition is considered necessary .
"Query string contains SQL injection threat after decoding as URL."

**Comment by marknca** [comment]
Agreed @fnifni but this is a limitation in AWS WAF and not the configuration. I've update the condition with [a commit](https://github.com/deep-security/aws-waf/commit/9b9493175593e8515a7563937aac2579be0587c1) but it's dependant on the mechanics of the rules engine, not this tool.
